# Generated by Django 4.0.1 on 2022-02-02 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeup', '0002_alter_brand_image_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=255, unique=True)),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=255, unique=True)),
        ),
    ]
