# Generated by Django 4.0.1 on 2022-01-30 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeup', '0002_alter_brand_name_alter_brand_orgin_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
