# Generated by Django 4.0.1 on 2022-01-30 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeup', '0004_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
