# Generated by Django 4.0.1 on 2022-02-08 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makeup', '0010_alter_customer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
